[package]
name = "service"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
crud = { path = "../crud" }
domain = { path = "../domain" }
async-trait = "0"
anyhow = "1"

[dev-dependencies]
tokio = "1"
